server:
  port: 3000
  host: localhost
  baseURL: https://65fd4a801b2c4ffefedc326b--fahimahmadi.netlify.app

database:
  host: localhost
  port: 27017
  name: decap_db

authentication:
  jwtSecret: "your_secret_key"
  expiresIn: "1d"
